name: casanet dashboard app CI CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1 
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Bundle www # The assets build for the public CDN
      env:
        BUILD_PATH: www
      run: |
        npm i -g yarn
        yarn install --frozen-lockfile
    - uses: actions/upload-artifact@v2
      with:
        name: www
        path: www
    - name: Bundle Android APK # The assets build for the Android APP
      uses: oxr463/setup-cordova@0.0.2
      with:
        exec: |
          cordova platform add android && \
          npm run release:android && \
          mkdir release && \
          cp "$(find . -name '*.apk')" ./release
    - uses: actions/upload-artifact@v2
      with:
        name: android 
        path: release
    - name: Bundle internal # The assets build for the local server, the api server is just ''
      env:
        REACT_APP_API_URL: ''
        BUILD_PATH: internal
      run: |
        yarn run build
    - uses: actions/upload-artifact@v2
      with:
        name: internal 
        path: internal
